name: check_code_quality
on: pull_request
jobs:
    black:
        runs-on : unbuntu-20.04
        steps:
         - uses: actions/checkout@v3
         - uses: action//setup-python@v4
           with:
               python-version: 3.9
         - run |
            python -m pip install --upgrade pip
            pip install black
         - run: |
            black --check --verbose .
